name: develop build test

on:
  pull_request:
    paths:
    - Projects/**
    - Tuist/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Show Xcode & Swift versions
      run: |
        xcodebuild -version
        swift --version

    - name: Setup mise
      run: |
        # Install mise
        curl https://mise.jdx.dev/install.sh | sh
        
        # Add mise to PATH for the entire workflow
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
        
        # Activate mise for the current shell
        eval "$(~/.local/bin/mise activate bash)"

    - name: Install Tuist CLI  
      run: |
        # Install Tuist using mise
        mise install tuist@4.36.0
        
        # Verify installation
        mise doctor

    - name: Cache Tuist and Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.tuist
          ~/.local/share/mise/plugins/tuist
          ~/Library/Caches/tuist
        key: tuist-cache-${{ runner.os }}-${{ hashFiles('**/Tuist/*.lock', '**/Tuist/Dependencies.swift', '**/Project.swift') }}
        restore-keys: |
          tuist-cache-${{ runner.os }}-
  
    - name: Conditional Tuist Clean
      id: check-clean
      run: |
        # Check if Tuist-related files changed
        if git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qE "Tuist/Dependencies.swift|Tuist/Project.swift|Tuist.lock"; then
          echo "run_clean=true" >> $GITHUB_ENV
        else
          echo "run_clean=false" >> $GITHUB_ENV
        fi

    - name: Tuist Clean
      if: env.run_clean == 'true'
      run: |
        tuist clean

    - name: Tuist install
      run: |
        tuist install

    - name: Tuist build
      run: |
        tuist build

    - name: Tuist Test
      if: ${{ vars.TUIST_TEST_ON_OFF == 'true' }}
      run: |
        tuist test
