name: develop build test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup mise
      run: |
        # Install mise
        curl https://mise.jdx.dev/install.sh | sh
        eval "$(~/.local/bin/mise activate bash)"
        mise doctor

    - name: Cache Tuist and Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.tuist
          ~/.local/share/mise/plugins/tuist
          ~/Library/Caches/tuist
        key: tuist-cache-${{ runner.os }}-${{ hashFiles('**/Tuist/*.lock', '**/Tuist/Dependencies.swift', '**/Project.swift') }}
        restore-keys: |
          tuist-cache-${{ runner.os }}-

    - name: Conditional Tuist Clean
      id: check-clean
      run: |
        # Check if Tuist-related files changed
        if git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qE "Tuist/Dependencies.swift|Tuist/Project.swift|Tuist.lock"; then
          echo "run_clean=true" >> $GITHUB_ENV
        else
          echo "run_clean=false" >> $GITHUB_ENV
        fi

    - name: Tuist Clean
      if: env.run_clean == 'true'
      run: |
        eval "$(~/.local/bin/mise activate bash)"
        tuist clean

    - name: Tuist Install
      run: |
        eval "$(~/.local/bin/mise activate bash)"
        tuist install

    - name: Tuist Build
      run: |
        eval "$(~/.local/bin/mise activate bash)"
        tuist build

    - name: Tuist Test
      if: ${{ vars.TUIST_TEST_ON_OFF == 'true' }}
      run: |
        eval "$(~/.local/bin/mise activate bash)"
        tuist test