name: develop build test pass

on:
  pull_request:
    paths-ignore:
    - Projects/**
    - Tuist/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Run empty
      run : echo "Not Build Test"