name: monday scheduler

on:
  # Run Korea time am 09:30 Monday
  schedule:
    - cron: "30 0 * * 1"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

permissions: write-all

jobs:
  monday_scheduler:
    name: scheduler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete old branches
        uses: beatlabs/delete-old-branches-action@v0.0.10
        with:
          repo_token: ${{ github.token }}
          default_branches: master
          date: '1 months ago'
          #dry_run true : 실제 삭제되지 않음. false: 실제로 삭제됨
          dry_run: false
          delete_tags: true
          minimum_tags: 5
          extra_protected_tag_regex: '^v.*'
          exclude_open_pr_branches: true
